/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPreferencesRouteImport } from './routes/_authenticated/preferences'
import { Route as AuthenticatedInvestRouteImport } from './routes/_authenticated/invest'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPreferencesRoute =
  AuthenticatedPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvestRoute = AuthenticatedInvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/invest': typeof AuthenticatedInvestRoute
  '/preferences': typeof AuthenticatedPreferencesRoute
}
export interface FileRoutesByTo {
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/invest': typeof AuthenticatedInvestRoute
  '/preferences': typeof AuthenticatedPreferencesRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/_authenticated/invest': typeof AuthenticatedInvestRoute
  '/_authenticated/preferences': typeof AuthenticatedPreferencesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/consent' | '/login' | '/invest' | '/preferences'
  fileRoutesByTo: FileRoutesByTo
  to: '/consent' | '/login' | '/invest' | '/preferences' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/consent'
    | '/login'
    | '/_authenticated/invest'
    | '/_authenticated/preferences'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ConsentRoute: typeof ConsentRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/preferences': {
      id: '/_authenticated/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof AuthenticatedPreferencesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invest': {
      id: '/_authenticated/invest'
      path: '/invest'
      fullPath: '/invest'
      preLoaderRoute: typeof AuthenticatedInvestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedInvestRoute: typeof AuthenticatedInvestRoute
  AuthenticatedPreferencesRoute: typeof AuthenticatedPreferencesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedInvestRoute: AuthenticatedInvestRoute,
  AuthenticatedPreferencesRoute: AuthenticatedPreferencesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ConsentRoute: ConsentRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
